name: Deploy to EC2
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd weather-app
          git pull
          sudo docker build -t weather-app .
          sudo docker stop weather-app || true
          sudo docker rm weather-app || true
          sudo docker run -d --name weather-app -p 80:8080 -e WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }} weather-app
